---
driver:
  name: vagrant
  cachier: true

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  ansible_verbose: true
  require_chef_for_busser: false
  playbook: test/role/main.yml
  requirements_path: test/role/requirements.yml

verifier:
  name: inspec

suites:
  - name: default