---
- block:
    - name: configure apt sources.list
      template:
        src:    sources.list.j2
        dest:   /etc/apt/sources.list
        backup: yes
        owner:  root
        group:  root
        mode:   0644
      register: apt_sources

    - name: update apt cache
      apt:
        update_cache: yes
      when: apt_sources.changed

  become: true
  become_method: sudo
  tags:
    - apt_sources_list
